apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
  name: keycloak-operator-clusterrole
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - ingresses
  verbs:
  - get
