apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.kubernetes.io/name: platform
  name: platform
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - oci://quay.holos.internal/holos/holos-paas-config
  - oci://quay.holos.internal/holos/holos-paas-manifests
