apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.kubernetes.io/name: projects
  name: projects
  namespace: argocd
spec:
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  - namespace: '!argocd'
    server: https://kubernetes.default.svc
  - namespace: '!kube-system'
    server: https://kubernetes.default.svc
  namespaceResourceBlacklist:
  - group: argoproj.io
    kind: Application
  - group: argoproj.io
    kind: AppProject
  - group: argoproj.io
    kind: ApplicationSet
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - oci://quay.holos.internal/*/*
