apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: holos-substrate-config
  namespace: argocd
stringData:
  insecure: "true"
  name: holos-substrate-config
  type: oci
  url: oci://quay.holos.internal/holos/holos-substrate-config
type: Opaque
