apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/component: application
    app.kubernetes.io/name: projects-application
    app.kubernetes.io/part-of: projects
  name: projects-application
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: projects
  source:
    directory:
      exclude: '**/workload/**'
      recurse: true
    path: clusters/k3d-holos/components/application
    repoURL: oci://quay.holos.internal/holos/holos-paas-config
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=false
