apiVersion: v1
data:
  config.yaml: |
    SERVER_HOSTNAME: quay.holos.localhost
    PREFERRED_URL_SCHEME: https
    EXTERNAL_TLS_TERMINATION: true
    SETUP_COMPLETE: true
    TESTING: false
    DB_URI: __DB_URI__
    SECRET_KEY: __SECRET_KEY__
    DATABASE_SECRET_KEY: __DATABASE_SECRET_KEY__
    BUILDLOGS_REDIS:
      host: quay-redis
      port: 6379
    USER_EVENTS_REDIS:
      host: quay-redis
      port: 6379
    DISTRIBUTED_STORAGE_CONFIG:
      default:
        - LocalStorage
        - storage_path: /datastorage/registry
    DISTRIBUTED_STORAGE_PREFERENCE:
      - default
    FEATURE_USER_CREATION: true
    FEATURE_USER_LOG_ACCESS: false
    FEATURE_DIRECT_LOGIN: false
    FEATURE_USERNAME_CONFIRMATION: false
    FEATURE_TEAM_SYNCING: true
    TEAM_RESYNC_STALE_TIME: 30m
    AUTHENTICATION_TYPE: OIDC
    KEYCLOAK_LOGIN_CONFIG:
      OIDC_SERVER: https://auth.holos.localhost/realms/holos/
      CLIENT_ID: https://quay.holos.localhost
      CLIENT_SECRET: __OIDC_CLIENT_SECRET__
      SERVICE_NAME: Holos SSO
      LOGIN_SCOPES:
        - openid
        - profile
        - email
        - groups
        - offline_access
      PREFERRED_USERNAME_CLAIM_NAME: preferred_username
      VERIFIED_EMAIL_CLAIM_NAME: email
      PREFERRED_GROUP_CLAIM_NAME: groups
      USE_PKCE: true
      PKCE_METHOD: S256
    SUPER_USERS:
      - svc-quay-resource-controller
      - quay-admin
    FEATURE_SUPERUSERS_FULL_ACCESS: true
    FEATURE_MAILING: false
    REGISTRY_TITLE: Holos Quay (quay)
    REGISTRY_TITLE_SHORT: Holos Quay
    DEFAULT_TAG_EXPIRATION: 2w
    TAG_EXPIRATION_OPTIONS:
      - 0s
      - 1d
      - 1w
      - 2w
      - 4w
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: quay
  name: quay-config-template
  namespace: quay
