apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: quay
  name: quay-datastorage
  namespace: quay
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
