apiVersion: v1
data:
  EXTERNAL_WEBHOOK_SERVER_BASE_URL: https://kargo-webhooks.holos.internal
  KARGO_NAMESPACE: kargo
  LOG_FORMAT: JSON
  LOG_LEVEL: INFO
  SYSTEM_RESOURCES_NAMESPACE: kargo-system-resources
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: external-webhooks-server
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kargo
    app.kubernetes.io/version: v1.10.3
    helm.sh/chart: kargo-1.10.3
  name: kargo-external-webhooks-server
  namespace: kargo
