apiVersion: v1
data:
  CLUSTER_SECRETS_NAMESPACE: kargo-cluster-secrets
  EXTERNAL_WEBHOOK_SERVER_BASE_URL: https://localhost
  KARGO_NAMESPACE: kargo
  LOG_FORMAT: JSON
  LOG_LEVEL: INFO
  MAX_CONCURRENT_NAMESPACE_RECONCILES: "4"
  MAX_CONCURRENT_PROJECT_CONFIG_RECONCILES: "4"
  MAX_CONCURRENT_PROJECT_RECONCILES: "4"
  MAX_CONCURRENT_SERVICE_ACCOUNT_RECONCILES: "4"
  SHARED_RESOURCES_NAMESPACE: kargo-shared-resources
  SYSTEM_RESOURCES_NAMESPACE: kargo-system-resources
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: management-controller
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kargo
    app.kubernetes.io/version: v1.10.3
    helm.sh/chart: kargo-1.10.3
  name: kargo-management-controller
  namespace: kargo
