apiVersion: v1
data:
  ALLOW_CREDENTIALS_OVER_HTTP: "false"
  API_SERVER_BASE_URL: https://kargo.holos.localhost
  ARGOCD_INTEGRATION_ENABLED: "true"
  ARGOCD_NAMESPACE: argocd
  ARGOCD_WATCH_ARGOCD_NAMESPACE_ONLY: "false"
  CACHE_BY_TAG_POLICY: Allow
  GIT_PUSH_INTEGRATION_POLICY: AlwaysRebase
  GITCLIENT_EMAIL: no-reply@kargo.io
  GITCLIENT_NAME: Kargo
  GITCLIENT_SIGNING_KEY_TYPE: gpg
  GITHUB_PUSH_MAX_REVISIONS: "10"
  GITHUB_PUSH_VERIFY_UNTRUSTED_COMMITS: "false"
  IMAGE_REGISTRY_RATE_LIMIT: "20"
  IS_DEFAULT_CONTROLLER: "true"
  LOG_FORMAT: JSON
  LOG_LEVEL: INFO
  MAX_CONCURRENT_CONTROL_FLOW_RECONCILES: "4"
  MAX_CONCURRENT_PROMOTION_RECONCILES: "4"
  MAX_CONCURRENT_STAGE_RECONCILES: "4"
  MAX_CONCURRENT_WAREHOUSE_RECONCILES: "4"
  MAX_IMAGE_CACHE_ENTRIES: "100000"
  MAX_OCI_PUSH_ARTIFACT_SIZE: "1073741824"
  MIN_WAREHOUSE_RECONCILIATION_INTERVAL: 5m0s
  ROLLOUTS_INTEGRATION_ENABLED: "false"
  SHARED_RESOURCES_NAMESPACE: kargo-shared-resources
  SYSTEM_RESOURCES_NAMESPACE: kargo-system-resources
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kargo
    app.kubernetes.io/version: v1.10.3
    helm.sh/chart: kargo-1.10.3
  name: kargo-controller
  namespace: kargo
