apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kargo
    app.kubernetes.io/version: v1.10.3
    helm.sh/chart: kargo-1.10.3
  name: kargo-api
  namespace: kargo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: kargo
      app.kubernetes.io/name: kargo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        configmap/checksum: 62f186b089a57be67a02119cfecd79b6ae70e92db0d5b63eb9491d307eb9055e
        secret/checksum: d1de5656a573b5d57005b49b298a3441cfb54788b06b84fb66979d84ba7389a1
      labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: kargo
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kargo
        app.kubernetes.io/version: v1.10.3
        helm.sh/chart: kargo-1.10.3
    spec:
      containers:
      - command:
        - /usr/local/bin/kargo
        - api
        env:
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              containerName: api
              divisor: "1"
              resource: limits.memory
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              containerName: api
              divisor: "1"
              resource: requests.cpu
        envFrom:
        - configMapRef:
            name: kargo-api
        - secretRef:
            name: kargo-api
        image: ghcr.io/akuity/kargo:v1.10.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          grpc:
            port: 8080
        name: api
        ports:
        - containerPort: 8080
          name: h2c
          protocol: TCP
        readinessProbe:
          grpc:
            port: 8080
          initialDelaySeconds: 5
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        startupProbe:
          failureThreshold: 30
          grpc:
            port: 8080
          initialDelaySeconds: 10
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: certs
      initContainers:
      - args:
        - |
          for file in /tmp/source/*; do
            base_filename=$(basename "$file" .crt)
            awk 'BEGIN {c=0;} /BEGIN CERT/{c++} { print > "/usr/local/share/ca-certificates/" base_filename "." c ".crt"}' base_filename="$base_filename" < $file
          done
          /usr/sbin/update-ca-certificates
          find /etc/ssl/certs -type l -exec cp --remove-destination {} /etc/ssl/certs/ \;
          cp -r /etc/ssl/certs/* /tmp/target/
        command:
        - /bin/sh
        - -c
        image: ghcr.io/akuity/kargo:v1.10.3
        imagePullPolicy: IfNotPresent
        name: parse-cabundle
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /tmp/source
          name: cabundle
        - mountPath: /tmp/target
          name: certs
      serviceAccount: kargo-api
      volumes:
      - name: cabundle
        secret:
          secretName: kargo-local-ca
      - emptyDir: {}
        name: certs
