apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/name: kargo
  name: kargo-external-webhooks-server-redirect-http
  namespace: kargo
spec:
  hostnames:
  - kargo-webhooks.holos.internal
  parentRefs:
  - name: default
    namespace: istio-gateways
    sectionName: http
  rules:
  - filters:
    - requestRedirect:
        scheme: https
        statusCode: 301
      type: RequestRedirect
