apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kargo
    app.kubernetes.io/version: v1.10.3
    helm.sh/chart: kargo-1.10.3
  name: kargo-shared-resources-reader
  namespace: kargo-shared-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-shared-resources-reader
subjects:
- kind: ServiceAccount
  name: kargo-user
  namespace: kargo
- kind: ServiceAccount
  name: kargo-viewer
  namespace: kargo
- kind: ServiceAccount
  name: kargo-project-creator
  namespace: kargo
