apiVersion: v1
data:
  app.host: my-app.holos.internal
  app.name: my-app
  app.port: "8080"
  app.project: my-project
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: my-app
  name: my-app
  namespace: my-project
