apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/name: echo
  name: echo
  namespace: echo
spec:
  hostnames:
  - echo.holos.localhost
  parentRefs:
  - name: default
    namespace: istio-gateways
  rules:
  - backendRefs:
    - name: echo
      port: 8080
