apiVersion: v1
kind: Namespace
metadata:
    annotations:
        kargo.akuity.io/keep-namespace: "true"
    labels:
        istio.io/dataplane-mode: ambient
        kargo.akuity.io/project: "true"
        kubernetes.io/metadata.name: prod-my-project
    name: prod-my-project
