apiVersion: v1
kind: Namespace
metadata:
    annotations:
        app.holos.run/my-app: my-app|my-project|registry.k8s.io/e2e-test-images/agnhost:2.53|8080
        kargo.akuity.io/keep-namespace: "true"
    labels:
        istio.io/dataplane-mode: ambient
        kargo.akuity.io/project: "true"
        kubernetes.io/metadata.name: prod-my-project
    name: prod-my-project
