---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakgroupmembership-editor-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - keycloak.holos.run
    resources:
      - keycloakgroupmemberships
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
