---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: holos-controller-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.holos.run
  resources:
  - keycloakclients
  - keycloakgroups
  - keycloakinstances
  - keycloakusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.holos.run
  resources:
  - keycloakclients/finalizers
  - keycloakgroups/finalizers
  - keycloakinstances/finalizers
  - keycloakusers/finalizers
  verbs:
  - update
- apiGroups:
  - keycloak.holos.run
  resources:
  - keycloakclients/status
  - keycloakgroups/status
  - keycloakinstances/status
  - keycloakusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - quay.holos.run
  resources:
  - organizations
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quay.holos.run
  resources:
  - organizations/finalizers
  - repositories/finalizers
  verbs:
  - update
- apiGroups:
  - quay.holos.run
  resources:
  - organizations/status
  - repositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security.holos.run
  resources:
  - referencegrants
  verbs:
  - get
  - list
  - watch
