apiVersion: v1
kind: ServiceAccount
metadata:
  name: holos-controller-manager
  namespace: holos-controller
  labels:
    app.kubernetes.io/name: holos-controller
    app.kubernetes.io/managed-by: kustomize
