apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: keycloak-config
  name: keycloak-config-89c64908
  namespace: keycloak
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak-config
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: KEYCLOAK_URL
          value: https://keycloak-service:8443
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: keycloak-initial-admin
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: keycloak-initial-admin
        - name: QUAY_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client_secret
              name: quay-oidc
        - name: SVC_QUAY_RESOURCE_CONTROLLER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: svc-quay-resource-controller
        - name: QUAY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: quay-admin
        - name: HOLOS_CONTROLLER_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client_secret
              name: svc-holos-controller-oidc
        - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
          value: "true"
        - name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
          value: 120s
        - name: KEYCLOAK_SSLVERIFY
          value: "false"
        - name: IMPORT_FILES_LOCATIONS
          value: /config/holos.json
        - name: IMPORT_VARSUBSTITUTION_ENABLED
          value: "true"
        - name: JAVA_OPTS
          value: -Djava.io.tmpdir=/tmp
        image: docker.io/adorsys/keycloak-config-cli:6.5.1-26.5.5
        name: keycloak-config
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
        - mountPath: /tmp
          name: tmp
      restartPolicy: Never
      securityContext:
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - configMap:
          name: keycloak-realm-config
        name: config
      - emptyDir: {}
        name: tmp
  ttlSecondsAfterFinished: 86400
