apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: holos-controller-manager-rolebinding
  labels:
    app.kubernetes.io/name: holos-controller
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: holos-controller-manager-role
subjects:
  - kind: ServiceAccount
    name: holos-controller-manager
    namespace: holos-controller
