apiVersion: security.holos.run/v1alpha1
kind: ReferenceGrant
metadata:
  labels:
    app.kubernetes.io/name: keycloak
  name: holos-keycloak-projects
  namespace: keycloak
spec:
  from:
  - group: keycloak.holos.run
    kind: Group
    namespace: my-project
  - group: keycloak.holos.run
    kind: GroupMembership
    namespace: my-project
  - group: keycloak.holos.run
    kind: User
    namespace: my-project
  - group: keycloak.holos.run
    kind: Client
    namespace: my-project
  to:
  - group: keycloak.holos.run
    kind: Instance
    name: holos-keycloak
