apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-holos-internal
  namespace: istio-gateways
spec:
  dnsNames:
  - '*.holos.internal'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: local-ca
  secretName: wildcard-holos-internal
