apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
    labels:
        app.kubernetes.io/name: echo
    name: test
    namespace: kargo-echo
spec:
    promotionTemplate:
        spec:
            steps:
                - config:
                    apps:
                        - name: echo
                          namespace: argocd
                          sources:
                            - desiredRevision: ${{ imageFrom("quay.holos.localhost/holos/holos-paas-manifests").Digest }}
                              repoURL: oci://quay.holos.localhost/holos/holos-paas-manifests
                              updateTargetRevision: true
                  uses: argocd-update
    requestedFreight:
        - origin:
            kind: Warehouse
            name: manifests
          sources:
            direct: true
