apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
    labels:
        app.kubernetes.io/name: echo
    name: manifests
    namespace: kargo-echo
spec:
    freightCreationPolicy: Automatic
    interval: 1m
    subscriptions:
        - image:
            allowTags: ^render-[0-9a-f]{12}-[0-9a-f]{12}$
            discoveryLimit: 20
            imageSelectionStrategy: Lexical
            insecureSkipTLSVerify: true
            repoURL: quay.holos.localhost/holos/holos-paas-manifests
            strictSemvers: true
