apiVersion: quay.holos.run/v1alpha1
kind: Organization
metadata:
  labels:
    app.kubernetes.io/name: my-project
  name: my-project
  namespace: my-project
spec:
  adopt: false
  credentialsSecretRef:
    name: holos-controller-quay-creds
  email: my-project@holos.localhost
  name: my-project
  syncedTeams:
  - name: my-project-owner
    oidcGroup: my-project-owner
    role: admin
  - name: my-project-editor
    oidcGroup: my-project-editor
    repositoryPermission: write
    role: creator
  - name: my-project-viewer
    oidcGroup: my-project-viewer
    repositoryPermission: read
    role: member
