apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "17"
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/name: platform-keycloak
    app.kubernetes.io/part-of: platform
  name: platform-keycloak
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: clusters/k3d-holos/components/keycloak
    repoURL: oci://quay.holos.internal/holos/holos-substrate-config
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=false
