apiVersion: keycloak.holos.run/v1alpha1
kind: KeycloakClient
metadata:
  labels:
    app.kubernetes.io/name: my-app
  name: my-app
  namespace: my-project
spec:
  clientId: https://my-app.holos.localhost
  clientRoles:
  - clientRef: my-app
    role: owner
  - clientRef: my-app
    role: editor
  - clientRef: my-app
    role: viewer
  instanceRef:
    name: holos-keycloak
    namespace: keycloak
  redirectUris:
  - https://my-app.holos.localhost/oauth2/callback
  secretRef:
    key: client_secret
    name: my-app-oidc
  type: confidential
  webOrigins:
  - https://my-app.holos.localhost
