apiVersion: v1
kind: Service
metadata:
  name: holos-authenticator
  labels:
    app.kubernetes.io/name: holos-authenticator
    app.kubernetes.io/managed-by: kustomize
    control-plane: authenticator-manager
spec:
  selector:
    control-plane: authenticator-manager
  ports:
    - name: grpc
      port: 9000
      protocol: TCP
      targetPort: grpc
