apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  labels:
    app.kubernetes.io/name: nats
  name: nats
  namespace: nats
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - nats
        - webhook-receiver
  selector:
    matchLabels:
      app.kubernetes.io/component: nats
      app.kubernetes.io/instance: nats
      app.kubernetes.io/name: nats
