apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: keycloak-service
  namespace: istio-gateways
spec:
  exportTo:
  - .
  host: keycloak-service.keycloak.svc.cluster.local
  trafficPolicy:
    tls:
      insecureSkipVerify: true
      mode: SIMPLE
