apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  labels:
    app.kubernetes.io/name: my-project
  name: my-project
  namespace: my-project
spec:
  promotionPolicies:
  - autoPromotionEnabled: true
    stage: project-config
  - autoPromotionEnabled: true
    stage: my-app-config
  webhookReceivers:
  - name: quay
    quay:
      secretRef:
        name: my-project-quay-webhook
