apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.kubernetes.io/name: my-project
  name: my-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: my-project
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - oci://quay.holos.localhost/my-project/*
