apiVersion: keycloak.holos.run/v1alpha1
kind: KeycloakGroup
metadata:
  labels:
    app.kubernetes.io/name: my-project
  name: my-project-roles-viewer
  namespace: my-project
spec:
  clientRoles:
  - clientId: https://quay.holos.localhost
    role: my-project-viewer
  - clientRef: my-project
    role: my-project-viewer
  custodians:
  - path: projects/my-project/custodians/viewer
  instanceRef:
    name: holos-keycloak
    namespace: keycloak
  path: projects/my-project/roles/viewer
